use AdoptersForLife
GO

--BULK INSERT accepts only absolute path, it has to be changed

BULK INSERT dbo.Animals FROM '\path\T1_animals_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A')
GO
BULK INSERT dbo.Volunteers FROM '\path\T1_volunteers_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A')
GO
BULK INSERT dbo.PAs FROM '\path\T1_PAs_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Preferences FROM '\path\T1_preferences_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Works FROM '\path\T1_works_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Adoption_processes FROM '\path\T1_adoption_processes_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Adoptions FROM '\path\T1_adoptions_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Walks FROM '\path\T1_walks_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Presentations FROM '\path\T1_presentations_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO

WAITFOR DELAY '00:00:30'
GO

BULK INSERT dbo.Animals FROM '\path\T2_animals_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Volunteers FROM '\path\T2_volunteers_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.PAs FROM '\path\T2_PAs_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Preferences FROM '\path\T2_preferences_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Works FROM '\path\T2_works_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Adoption_processes FROM '\path\T2_adoption_processes_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Adoptions FROM '\path\T2_adoptions_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Walks FROM '\path\T2_walks_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
BULK INSERT dbo.Presentations FROM '\path\T2_presentations_DB.csv' WITH (FIELDTERMINATOR='|', ROWTERMINATOR='0x0A', FIRSTROW=2)
GO
